Add main app and urls
SaparinOleg/django_lessons pull request #1
Opened 2023-10-05 20:41 UTC by SaparinOleg

2023-10-07 07:43 UTC, PonomaryovVladyslav reviewed
В целом ок, но звездочку убери

2023-10-07 07:43 UTC, PonomaryovVladyslav commented on django_blog/main/urls.py
> +from .views import *
Никогда не используй импорт через звездочку, работать то все будет, но можно столкнутся с кучей проблем с циклическими импортами, только по одному

2023-10-07 07:45 UTC, PonomaryovVladyslav requested changes, later dismissed
Не туда тыкнул в первый раз:)

2023-10-10 15:23 UTC, SaparinOleg commented on django_blog/main/urls.py
> +from .views import *
Исправил импорты в bc1c4d0.
https://github.com/SaparinOleg/django_lessons/blob/bc1c4d0314df88b4836f1ddb32b795e90f063bfa/django_blog/main/urls.py#L2-L20

2023-10-10 15:26 UTC, PonomaryovVladyslav approved these changes

2023-10-10 15:35 UTC, merged